set(DOXYGEN_EXECUTABLE doxygen CACHE STRING "Doxygen command to use")
set(SPHINX_EXECUTABLE sphinx-build CACHE STRING "Sphinx build command to use")

add_custom_target(
    docs
    COMMAND "${CMAKE_COMMAND}"
    -D "DOXYGEN_EXECUTABLE=${DOXYGEN_EXECUTABLE}"
    -D "SPHINX_EXECUTABLE=${SPHINX_EXECUTABLE}"
    -D "PROJECT_SOURCE_DIR=${PROJECT_SOURCE_DIR}"
    -D "PROJECT_BINARY_DIR=${PROJECT_BINARY_DIR}"
    -P "${PROJECT_SOURCE_DIR}/cmake/docs.cmake"
    WORKING_DIRECTORY "${PROJECT_SOURCE_DIR}"
    COMMENT "Building docs"
    VERBATIM
)
