name: Benchmark

on:
  workflow_dispatch:

jobs:
  benchmarks:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image (cached)
      uses: docker/build-push-action@v6
      with:
        context: .
        tags: chesscxx:latest
        load: true
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Cache ccache directory
      uses: actions/cache@v4
      with:
        path: ~/ccache
        key: ${{ runner.os }}-ccache-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-ccache-

    - name: Cache ctcache directory
      uses: actions/cache@v4
      with:
        path: ~/ctcache
        key: ${{ runner.os }}-ctcache-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-ctcache-

    - name: Configure
      run: docker run --rm -v $(pwd)/:/chesscxx -w /chesscxx chesscxx:latest cmake --preset=ci-ubuntu

    - name: Build
      run: |
        docker run --rm -v $(pwd)/:/chesscxx -v ~/ccache:/root/.cache/ccache -v ~/ctcache:/tmp/ctcache-root -w /chesscxx chesscxx:latest \
        sh -c "
          ccache -p && ccache -s && ccache -z &&
          clang-tidy-cache --cache-dir && clang-tidy-cache --show-stats && clang-tidy-cache --zero-stats &&
          cmake --build build --config Release -j \$(nproc) &&
          ccache -s && clang-tidy-cache --show-stats
        "

    - name: Run benchmarks
      run: |
        docker run --rm --privileged -v $(pwd)/:/chesscxx -w /chesscxx chesscxx:latest \
        sh -c "echo 0 > /proc/sys/kernel/randomize_va_space && cmake --build build -t run-benchmarks"
